/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package weather;

import java.io.IOException;
import java.util.*;

import com.jxgm.dao.*;
import com.jxgm.entities.*;

import com.jxgm.DBConnection.DB;

import java.sql.*;


public class App {
    private static ProvDao provDao = new PlainProvDao();
    private static CityDao cityDao = new PlainCityDao();

    public static void main(String[] args) throws IOException {

        DB db = new DB();
        Connection con = null;

        try {
            con = DB.getCon();

            Province p = provDao.findById("16");
            System.out.println(p);
            
            List<City> cities = cityDao.findByPid("16");
            // cities.forEach((City c) -> {
            //     System.out.println(c);
            // });

            p.setCities(cities);
            System.out.println(p.getCities());

        } catch(Exception e) {
		} finally {
			try {
				db.closeCon(con);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
    }
}
